### ISSUE TITLE
Roadmap next major release (v2.0?)

### ISSUE THREAD

**Issue by JrSchild** [chaijs/chai-json-schema#26]
At least the following things should happen before the next release. I think having a better integration with Enrise's team ensures code quality, process management and release cycles. For now this project is mostly maintenance and making sure everything is up to date with today's standards.
- [ ] Resolve current tickets
- [ ] Discuss other things to do for a major release
- [ ] Rewrite tests
- [ ] eslint instead of jshint
  - [ ] Update styling
  - [ ] Grunt & Travis
- [ ] .editorconfig file
- [ ] Test coverage integration
- [x] Run travis with more modern versions of node
  - [x] Update package.json to support newer versions
  - [x] Drop old legacy versions?
- [x] Update labels for better integration with the team
- [x] ~~Release minor version on NPM (1.3.0)~~
- [x] ~~Discuss receiving more control over the project so we can manage our team internally~~
- [x] ~~Review the commits that I made yesterday~~
- [x] ~~Update (dev)dependencies~~
- [x] ~~Update peerDependencies for compatibility with chai 3.0+~~
- [x] ~~Indentation: two spaces instead of tabs~~
- [x] ~~Fix the tests~~
- [x] ~~Merge PR's~~
- [x] ~~Update buttons and such in README~~
- [x] ~~Drop support for node 0.10~~
- [x] ~~Update bower.json~~

**Comment by Niklv** [comment]
What about switching to https://github.com/epoberezkin/ajv ?

**Comment by keithamus** [comment]
@JrSchild I think it'd be great if all projects under the `chaijs` org all follow the same standards. If you have a look at https://github.com/chaijs/type-detect or https://github.com/chaijs/deep-eql or https://github.com/chaijs/pathval you can see we where we're going with this. All these projects use the same lint config (eslint-config-strict), the same release management tools (semantic-release) and the same tooling (npm scripts). My ideal would be for every project to fall in line with that. Thoughts?

**Comment by thabemmz** [comment]
@Niklv thanks for the suggestion, we'll look into it.

**Comment by JrSchild** [comment]
Hi @keithamus.
With the latest release we synchronized node support (in Travis) with chai core. There is still some maintenance to do and the tests really need a rewrite. Including eslint is definitely something that we want to integrate in the future. Ultimately synchronizing with the `chaijs` standards is where we would like to go.

**Comment by Niklv** [comment]
@thabemmz there is a benchmark https://github.com/ebdrup/json-schema-benchmark

**Comment by edwardsmit** [comment]
@scottux No such plans.
